treasure-data/omnibus-td-agent

templates/etc/init.d/deb/td-agent
On Debian/Ubuntu, init script doesn't respond to `reload`. It should be reloadable as same as on RedHat.
=> Enable `reload` in init script for Debian/Ubuntu

templates/package-scripts/td-agent/deb/prerm
When I removed td-agent version 2 package, td-agent processes were still alive.
I had no choice but to do `kill PID`.
This patch removes package after stoping processes like td-agent version 1.
=> add prerm for debian

templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
Just added `set -e` at the beginning of the init scripts to exit as non-zero on some errors.
=> Exit as error if one of a commans exists with non-zero

config/projects/td-agent2.rb, config/software/liblzma.rb
This patch is applied to td-agent 2.1.3-1.
=> Fix lzma undefined issue at plugin installation on CentOS 7

config/software/td-agent-files.rb, config/software/td-agent-ui.rb, config/software/td.rb
A space between '->' and '(' does not parse in ruby 1.9,
with no space it works in both 1.9 and 2.0+.
=> Remove spaces in lambda rockets for ruby 1.9

templates/etc/init.d/deb/td-agent
Additional fix for #23 to make Debian init script compliant to the [Debian Policy Manual](https://www.debian.org/doc/debian-policy/ch-opersys.html#s-writing-init).
Changes:
1. `start` service on `restart` if it's not running
1. do `configtest` before `restart` and `reload` then exit with non-zero if there are problems
1. show message on failed `configtest`
=> Fix init script for Debian to respect return values

templates/package-scripts/td-agent/deb/postinst, templates/package-scripts/td-agent/deb/postrm, templates/package-scripts/td-agent/deb/prerm
But omnibus doesn't use db_xxx helpers so we replace #DEBHELPER#
with actual code manually.
Copy code from td-agent 1's scripts.
=> Replace #DEBHELPER# with actual code. fix #29

config/projects/td-agent2.rb, config/software/postgresql.rb, config/software/td-agent.rb
Omnibus has own OpenSSL and it causes pg gem can't be installed
because pg gem depends on system OpenSSL.
We will remove own OpenSSL dependency from omnibus package.
This patch is for short-term approach to resolve pg gem issue.
=> Include PostgreSQL for pg related plugins

templates/etc/init.d/rpm/td-agent
I confirmed that the `status` function defined in RedHat's `/etc/init.d/functions` doesn't work well with `set -e` enabled. As reported in #31, current init script will return non-zero even if service process is running. I set `set +e` just before calling `status` to allow errors in the function. This is just a workaround but will work as expected.
=> Fix `status` in init script for RedHat

templates/etc/init.d/deb/td-agent
Currently, init.d script commands (`start`, `stop`, `reload`, `restart`) show meaningful display name `$NAME`.
However, the `status` command show meaningless display name `ruby`.
I think that all commands should show meaningful display name.
=> Use meaningful display name `$NAME` instead of meaningless name `ruby`

templates/package-scripts/td-agent/deb/postrm
When I purged td-agent version 2 package, config files that `postinst` made still existed.
This patch removes config files when purge td-agent version 2 package.
=> remove config files when doing apt-get remove --purge

omnibus.rb
I add the option `append_timestamp false` which avoids adding timestamp to `build_version` for latest `omnibus`.
=> use omnibus from github

.gitignore, Rakefile, bats/configtest_debian.bats, bats/configtest_redhat.bats, bats/reload_debian.bats, bats/reload_redhat.bats, bats/render, bats/restart_debian.bats, bats/restart_redhat.bats, bats/start_debian.bats, bats/start_redhat.bats, bats/status_debian.bats, bats/status_redhat.bats, bats/stop_debian.bats, bats/stop_redhat.bats, bats/stubs/stub, bats/test_helper.bash, config/software/td-agent-files.rb, templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
There should be tests even for init scripts. I wrote tests with using https://github.com/sstephenson/bats . Test coverage is still not so good, but I believe it's sufficient for starter.
I also fixed unintended init script behaviour (==> bugs) found during testing. I believe this should solve the problems of init script like #42 .
1. Added a new template variable `root_path`
1. Added guard for potential problem found in RedHat's init functions (92f9cde286bf506f0496ce4b154c16faa7976108, 3714daead5e3a09767847f4bcea108d06b6245f9)
1. The `restart` action should fail immediately if `configtest` failed (dd63b6e05f46b72d17063ffdfc493a0ea9f22f77)
1. The `restart` action should not fail immediately on `do_stop` failure since it might mean the old process has already been stopped …
=> There should be tests even for init scripts

.gitignore, .travis.yml, Rakefile, bats/compat_debian.bats, bats/compat_redhat.bats, bats/override_debian.bats, bats/override_redhat.bats, bats/reload_debian.bats, bats/restart_redhat.bats, bats/start_debian.bats, bats/start_redhat.bats, bats/stop_redhat.bats, bats/test_helper.bash, bats/usage_debian.bats, bats/usage_redhat.bats, config/software/td-agent-files.rb, templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
1. Removed `set -e` from RedHat init script to solve #42
1. Allow configuring td-agent parameters via variables (e.g. `TD_AGENT_USER`) declared in default file
1. Fixed coding style issue in init scripts
1. Add tests and tests and tests, to avoid future regression
=> Extra bats tests, including configurable td-agent arguments 

config/software/cacerts.rb
Fixes https://github.com/treasure-data/omnibus-td-agent/issues/38
Itamae uses same approach.
=> Latest cacert removes several certificates including AWS's one

bats/compat_debian.bats, bats/compat_redhat.bats, bats/configtest_debian.bats, bats/configtest_redhat.bats, bats/override_debian.bats, bats/override_redhat.bats, bats/start_debian.bats, bats/start_redhat.bats, bats/test_helper.bash, bats/usage_debian.bats, templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent, templates/package-scripts/td-agent/deb/postinst
It's not possible to override default td-agent's options (e.g. `--use-v1-config`) for now. To be honest, it was possible with RedHat, it requires specify whole td-agent arguments in `TD_AGENT_ARGS`, though.
I added `TD_AGENT_OPTIONS` to specify extra options for td-agent. This PR was prepared to keep compatibility between existing configuration variables of `DAEMON_ARGS` and `TD_AGENT_ARGS`. So, I believe this won't break any existing installation of td-agent.
=> Add `TD_AGENT_OPTIONS`

bats/restart_debian.bats, bats/stop_debian.bats, templates/etc/init.d/deb/td-agent
The second `start-stop-daemon --stop`, which doesn't have `--pidfile`
option, kills all td-agents including td-agent inside a container.
=> Don't call `start-stop-daemon --stop` twice

bats/stop_debian.bats, templates/etc/init.d/deb/td-agent
Need a way to control stop timeout. Related to https://github.com/treasure-data/omnibus-td-agent/pull/47
=> Add STOPTIMEOUT to deb init script

bats/compat_debian.bats, bats/compat_redhat.bats, bats/configtest_debian.bats, bats/override_debian.bats, bats/reload_debian.bats, bats/reload_redhat.bats, bats/restart_debian.bats, bats/restart_redhat.bats, bats/start_debian.bats, bats/status_debian.bats, bats/status_redhat.bats, bats/stop_debian.bats, bats/stop_redhat.bats, bats/test_helper.bash, templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
Added a same function in init script of both Debian and RedHat, to try to make their scripts common. With current impl, the actions of `reload` and `status` became common. We still need to make `do_start` and `do_stop` common eventually, but I think it requires some extra package like `redhat-lsb`.
In this PR, I believe this won't corrupt existing behaviour of the scripts. It'd be better to test on actual installation, though.
=> Add a function to send signal from `TD_AGENT_PID_FILE`

bats/status_redhat.bats, templates/etc/init.d/rpm/td-agent
`log_success_msg` and `log_failure_msg` are not defined in RedHat's `/etc/init.d/functions`. They were added by my mistake :disappointed: 
We need to add `redhat-lsb` as a dependency of rpm before using them. Meanwhile, I reverted the use of those functions by `echo`.
=> `log_success_msg` and `log_failure_msg` are not defined on RedHat

templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
In #45 the daemon name was hardcoded to "td-agent", so if the agent
name is changed the init script will not work.
=> Expand project_name in TD_AGENT_BIN_FILE

config/projects/td-agent2.rb, config/software/cacerts.rb
- Update cacerts to latest version (2015.09.02)
- Pull chef/omnibus-software#477 into this project
=> Workaround for cacerts build breakage

config/projects/td-agent2.rb
Rubygems 2.1 has a bug with processing < and <= in gemspecs which is fixed in 2.4.8.
see https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/54
and https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/commit/f33f9d04263b614425e7c2fdb2ea67536a714b6b
@trekdemo @nshttpd
=> Update rubygems to 2.4.8

Gemfile
```
$ bundle install --binstubs
Fetching git://github.com/chef/omnibus.git
Fetching git://github.com/opscode/omnibus-software.git
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies........................................
Bundler could not find compatible versions for gem "celluloid":
In Gemfile:
berkshelf (~> 3.0) was resolved to 3.0.0, which depends on
celluloid (~> 0.16.0.pre)
berkshelf (~> 3.0) was resolved to 3.0.0, which depends on
celluloid-io (~> 0.16.0.pre) was resolved to 0.16.5.pre0, which depends on
celluloid (>= 0.17.0.pre12)
Bundler could not find compatible versions for gem "multipart-post":
In Gemfile:
berkshelf (~> 3.0) was resolved …
```
=> To avoid dependency probrem.

config/projects/td-agent2.rb, config/software/td-agent.rb
Fixes #78 
@repeatedly I was able to make it work by using `runtime_dependency`, along with some other changes:
- Checking `ohai["os"]` instead of `ohai["platform"]`
- Moving from the software definition to the project configuration, since `runtime_dependency` only applies to projects
- Using `redhat-lsb-core` instead of `redhat-lsb`, since `redhat-lsb` pulls in unnecessary packages like `cups` and `qt`
I've only tested this on CentOS, so I wouldn't merge the without additional testing.
=> Fix LSB dependencies

Gemfile, config/software/fluentd.rb
Hello. fix build error for Ruby 2.1 or later.
1. fluentd default_version => fluentd v0.12.23 (latest release)
1. specify omnibus version
build environment: Ubuntu 16.04 / Ruby 2.3.1
----------
First, fix this error.
```
+ bundle exec bin/omnibus build td-agent2
The following shell command exited with status 1:
$ /opt/td-agent/embedded/bin/gem install --no-ri --no-rdoc pkg/fluentd-*.gem
Output:
(nothing)
Error:
ERROR:  Error installing pkg/fluentd-0.12.20.gem:
string-scrub requires Ruby version < 2.1, >= 1.9.3.
```
fluentd v0.12.23 including new dependency `string-scrub`
see: https://github.com/fluent/fluentd/pull/933,   https://github.com/fluent/fluentd/pull/937
----------
Second, fix this error.
```
+ bundle exec bin/omnibus build td-agent2 …
```
=> Fix build error for Ruby 2.1 or later.

README.md
`https://downloads.vagrantup.com/` shows Privacy Error in Chrome.
Fix this link to latest one.
=> Fix an old link to Vagrant download site

Gemfile
Omnibus 5.5 fails to build and as noted in issue https://github.com/treasure-data/omnibus-td-agent/issues/113 the fix is to use the master omnibus branch in the Gemfile.
=> Use latest version of omnibus to address issue #113

README.md
As 2.1 now results in the following error:
Bundler could not find compatible versions for gem "ruby ":
In Gemfile:
ruby
omnibus-software was resolved to 4.0.0, which depends on
omnibus (>= 5.5.0) was resolved to 5.5.0, which depends on
ruby  (>= 2.2)
=> Updated Ruby version number to 2.2 dependancy

templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
quickfix for #125
on systemd systems, systemd-sysv-generator converts the init script into
a unit file. without the pidfile, the service will stay active even
after exiting
however this is just a quickfix, an actual service file would be better
=> add pidfile chkconfig style comment to init scripts

templates/package-scripts/td-agent/deb/postinst
This will make sure to remove whatever is there file or symlink in the install path. Currently we have an issue as after we use some logic that makes runit the main init system so it creates a symlink in the install location after the package is installed which all works fine, but when you upgrade because there is a symlink in /etc/init.d/td-agent it instead installs the init.d script at /usr/bin/sv and replaces our sv binary. This fix shouldn't be an issue for anything else as all it does is make sure to remove the symlink or file at /etc/init.d/td-agent before writing the file there.
=> Don't follow a symlink replace /etc/init.d/td-agent with the script no matter what is there

bats/restart_debian.bats, bats/restart_redhat.bats, templates/etc/init.d/deb/td-agent, templates/etc/init.d/rpm/td-agent
`do_stop` is implemented to return 1 if the process has already stopped. However, `do_restart` was  implemented to exits as error  if the previous process has already stopped.
https://github.com/treasure-data/omnibus-td-agent/blob/18041dc0072910290c504f0a0cf4ae7941ce9ad6/templates/etc/init.d/deb/td-agent#L135
According to LSB, `restart` action of init script should start service for such cases.
> restart stop and restart the service if the service is already
> running, otherwise start the service
http://refspecs.linuxbase.org/LSB_2.0.1/LSB-PDA/LSB-PDA/iniscrptact.html
(cc: @repeatedly  @mururu )
=> td-agent should be started with restart action even if the previous process has already stopped

templates/etc/systemd/td-agent.service.erb
I'm not sure what is the exact cause but adding `RuntimeDirectory` is better for safety when `/var/run/td-agent` is missing.
I tested new systemd file and it worked if `/var/run/td-agent` exists.
=> Add RuntimeDirectory to prevent unexpected error. fix #155

templates/etc/systemd/td-agent.service.erb
In sysvinit days, we could use the env variable `TD_AGENT_OPTIONS`
to override the verbosity of td-agent (as explained in the following
documents):
https://docs.fluentd.org/v0.12/articles/trouble-shooting
This commit adds an equivalent mechanism to the systemd service file.
For the motivation behind this patch, please see the issue #161.
=> systemd: Support TD_AGENT_OPTIONS to override the command-line options.

Vagrantfile
I've confirmed that I can build td-agent deb package on vagrant box.
=> Add Debian stretch (9.3)

Vagrantfile
Ubuntu 18.04 also has same tar problem so remove omnibus's tar
=> Add Ubuntu 18.04 build image

templates/package-scripts/td-agent/rpm/post
rpm upgrade is overwriting /etc/logrotate.d/td-agent all the time. There should be a way to prevent this.
=> package-scripts: don't overwrite existing /etc/logrotate.d/td-agent

Gemfile.lock, config/projects/td-agent3.rb, config/software/postgresql.rb, config/software/rubygems.rb, core_gems.rb, plugin_gems.rb
Will be merged after https://github.com/treasure-data/omnibus-td-agent/pull/165
=> Release 3.2.0

bin/gem_downloader, config/software/bundler.rb, config/software/fluentd-ui.rb, config/software/fluentd.rb, config/software/rubygems.rb, config/software/td-agent.rb
Hi, since the `-no-ri -no-rdoc` option has been removed in rubygems 3.0.0. So, I replaced with `-no-document`.
=> replace `--no-ri --no-rdoc` to `--no-document`

templates/etc/init.d/rpm/td-agent
When nsswitch.conf is configured to use AD first (in our case centrifydc) for groups, running a 'getent group' command before the cache has synced can take a long time. With thousands of groups the td-agent service actions hang whilst it performs this lookup.
If td-agent is always a local group we can speed up the grep time by specifying the 'files' service (i.e. /etc/group) for the getent command.
Tested on RHEL 7.6.
=> search local service only for td-agent group

templates/etc/systemd/td-agent.service.erb
allows for vars to be sourced from /etc/sysconfig/td-agent when using systemd
=> updated to source variables

Vagrantfile, config/projects/td-agent3.rb, config/software/td-agent.rb
Current build doesn't support SASL.
If build environment has SASL related package, rdkafka gem is built with SASL support.
=> Build rdkafka gem with SASL support

.kitchen.yml
`kitchen converge` failed. The log is here.
```
$ chef --version
Chef Development Kit Version: 3.9.0
chef-client version: 14.12.3
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 1.24.0
inspec version: 3.9.3
$ cd omnibus-td-agent
$ bundle exec kitchen converge default-ubuntu-1404
-----> Starting Kitchen (v1.20.0)
$$$$$$ Deprecated configuration detected:
require_chef_omnibus
Run 'kitchen doctor' for details.
...
...
Setting up chef (12.4.1-1) ...
Thank you for installing Chef!
Transferring files to <default-ubuntu-1404>
Starting Chef Client, version 12.4.1
...
...
================================================================================
Recipe Compile Error in /tmp/kitchen/cache/cookbooks/chef-sugar/libraries/chef-sugar.rb …
```
=> Update kitchen file format and Use Chef 13

templates/package-scripts/td-agent/rpm/post
if environment variable TD_AGENT_USER and/or TD_AGENT_GROUP are set,  rpm package looks at them and use them as a group and/or user of td-agent.
=> Enable specifying user name at installing time

td-agent-on-windows.md
I've found that the described instruction didn't cover makeappx.exe where it exists in each of Windows Kits directories.
Because makeappex.exe does not exist in C:\Program Files (x86)\Windows Kits\10\bin\x64.
Instead, it exists in C:\Program Files (x86)\Windows Kits\10\bin\10.0.<BUILD NUMBER>.0\x64.
=> Add makeappex.exe instruction

config/projects/td-agent3.rb, resources/td-agent/msi/source.wxs.erb
`td-agent.conf` should be preserved during upgrading and repairing installation process.
Note that this fix will work after the next version of td-agent (parhaps 3.5.0-1?).
Because Windows installer uses registry as a marker to handle installed contents.
The previous version of td-agent does not use `NeverOverwrite` and `Permanent` attributes.
Thus, Windows installer has no idea how `td-agent.conf` should handle.
* Upgrade from td-agent 3.4.1 or older version to the next version of td-agent.
* Repair installation with the next version of td-agent.
* Upgrade from the next version of td-agent to the two next version of td-agent.
---
Is this fix expected behavior?
Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>
=> Implement config file preservation for MSI

config/software/td-agent.rb
In macOS => .dylib
Others => .so
see: https://github.com/appsignal/rdkafka-ruby/blob/master/ext/Rakefile#L38-L41
~~And rdkafa-ruby always uses Homebrew's OpenSSL.~~
~~Should we also consider to use OpenSSL libraries in td-agent package?~~
~~see: https://github.com/appsignal/rdkafka-ruby/blob/master/ext/Rakefile#L26-L29~~
I reported the library issue in https://github.com/appsignal/rdkafka-ruby/pull/102.
I can build td-agent package in my MacBookPro with this change.
=> Fix librdkafka Ruby extension file ext in whitelist_file

templates/package-scripts/td-agent/rpm/post
`'${PROJECT_USER}'` is passed as literal string to `useradd` in the RPM post-install script
```
Source RPM  : td-agent-3.5.1-0.el7.src.rpm
/usr/sbin/useradd -r -g ${PROJECT_GROUP} -d /var/lib/${PROJECT_USER} -s /sbin/nologin -c '${PROJECT_USER}' ${PROJECT_USER}
```
```
td-agent:x:111:222:${PROJECT_USER}:/var/lib/td-agent:/sbin/nologin
```
=> Fix useradd interpolation bug in rpm post-install script

templates/etc/systemd/td-agent.service.erb
**Motivation**
In the older init.d scripts the log path was parameterized, which allowed convenient customization using the environment file. In the new systemd `ExecStart`, the log path is hard-coded to `/var/log/td-agent/td-agent.log`. We should allow users to override the log path just like the init.d script
=> systemd: Support TD_AGENT_LOG_FILE to override command line options

plugin_gems.rb
Popular OSes now use systemd by default.
So bundle fluent-plugin-systemd is reasonable.
=> Bundle fluent-plugin-systemd

config/projects/td-agent3.rb, config/software/ruby.rb, resources/td-agent/msi/source.wxs.erb
TDAgentConf should be added in ProjectFeature.
Otherwise we got the following WiX error but WiX creates msi package:
error LGHT0204 : ICE21: Component: 'TDAgentConf' does not belong to any Feature.
And unused InstallDir parameter should be removed parameters which are pass-throughed into WiX script.
Because Ruby 2.4 or later depends on MSYS2, and MSYS2 recently uses
fortiled functions by default.
We should adopt this change on omnibus-td-agent because Ruby 2.3
had been marked as EOL in the previous year.
So, we should migrate building process on Windows to use Ruby 2.4+.
Otherwise, without this change, omnibus-td-agent complains the following error
with Ruby 2.4+ and MSYS2:
```log
Error:
C:/Ruby25-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin …
```
=> Tweak windows msi package

config/projects/td-agent3.rb, templates/etc/init.d/rpm/td-agent
This PR makes to remove redhat-lsb-core package runtime dependency.
I'd confirmed that rpm package building and confirmation on testkitchen's default-centos-75.
=> Remove lsb-core dependency from RPM package

templates/etc/init.d/rpm/td-agent
getent should handle a parameter to retrieve specific key.
From man getent:
```
passwd    When no key is provided, use setpwent(3), getpwent(3), and endpwent(3) to enumerate the passwd database.  When one or more key arguments are provided, pass each numeric  key  to
getpwuid(3) and each nonnumeric key to getpwnam(3) and display the result.
```
When a key for searching passwd entries is not provided, getent passwd should enumerate passwd entries entirely.
When a key for searching passwd entries is provided, getent passwd [a key] should returns an entry which is related to [a key].
=> Use ${TD_AGENT_USER} key on getent to prevent retriving entire passwd entries

templates/etc/init.d/rpm/td-agent
This is also needed to prevent retrieving huge group database by enumeration.
=> Use ${TD_AGENT_USER} key on getent to prevent retriving entire group entries

config/projects/td-agent3.rb
We can also remove lsb-core on CentOS 6.
If there is no lsb-core installation, users just get non-colorized
output for service command result.
And I'd confirmed that patched td-agent package should not pull lsb-core as dependent package:
```
[vagrant@default-centos-66 omnibus-td-agent]$ sudo yum install pkg/td-agent-3.8.0-0.el6.x86_64.rpm
読み込んだプラグイン:fastestmirror
インストール処理の設定をしています
pkg/td-agent-3.8.0-0.el6.x86_64.rpm を調べています: td-agent-3.8.0-0.el6.x86_64
pkg/td-agent-3.8.0-0.el6.x86_64.rpm をインストール済みとして設定しています
Loading mirror speeds from cached hostfile
* base: ftp.tsukuba.wide.ad.jp
* centos-sclo-rh: ftp.tsukuba.wide.ad.jp
* centos-sclo-sclo: ftp.tsukuba.wide.ad.jp
* epel: nrt.edge.kernel.org
* extras: ftp.tsukuba.wide.ad.jp
* updates: ftp.tsukuba.wide.ad.jp
依存性の解決をしています
--> …
```
=> Remove lsb-core dependency on CentOS 6

config/projects/td-agent3.rb
Because nokogiri 1.11.0 requests to use Ruby 2.5 or later.
omnibus-td-agent still needs to stay on Ruby 2.4.
Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>
=> Use nokogiri 1.10.10 constraint

resources/td-agent/msi/source.wxs.erb
Reported by @zubrahzz
ref. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28169
In the previous version, NT AUTHORITY\Authenticated Users:(I)(M) is
granted. It means that logged in users can replace any files under
opt/td-agent/bin. It also allows for attacker to gain administrative
privileges by replacing these files because these files are executed
as a local services with SYSTEM privilege.
Note that this PR was merged, we need to update gems
by td-agent-gem with administraror privilege.
=> windows: mitigate possible escalation of privileges

core_gems.rb
I'd succeeded to build td-agent 3.8.1 with these changes.
* Specify protocol-http/http2 version explicitly to stay Ruby 2.4 world
* Use nio4r 2.5.2 to avoid devkit which is provided by RubyInstaller2's Ruby requiring forcibly
=> Building td agent 3.8.1 on windows
